### ISSUE TITLE
[Task List] 0.9.2 Release - 20230228

### ISSUE THREAD

**Issue by Starnop** [sealerio/sealer#2001]
## Issue Description

Type: *feature request*

### Universal capability
- [x] support multi-arch for sealer image
- [ ] support e2e test #1966
   - [x] support e2e test CI
   - [ ] test coverage reaches 30 percent
   - [x] support running e2e test locally
- [ ] Performance, disk usage optimization
   - [ ]  use image cache when build stage

### APP Image Related
- [x] support image policy with Kyverno
- [x]   continue to improve APP,APPCMDS instruction for Kubefile and related config for Clusterfile
- [ ] completely decouple the app image from the cluster image
  - [ ] run app image on any declared supported versions of the kubernetes cluster 
- [x] support for concurrent deployment of applications 
- [x] https://github.com/sealerio/sealer/issues/2017
### Cluster Image Related
- [x] support upgrade kubernetes cluster
- [x] support Linux user with root privileges to install ClusterImage  #1999 
- [x] support more container runtime
  - [x] support containerd
- [x] support more cluster runtime
  - [x] support k0s cluster runtime

### Bugfix
- [x] https://github.com/sealerio/sealer/issues/2000 @Stevent-fei 
- [x] https://github.com/sealerio/sealer/issues/1998 @Stevent-fei 
- [x] https://github.com/sealerio/sealer/issues/1995 @Starnop 
- [x] https://github.com/sealerio/sealer/issues/1994 @Stevent-fei
- [x] https://github.com/sealerio/sealer/issues/1993 @kakaZhou719 
- [x] https://github.com/sealerio/sealer/issues/1989 @kakaZhou719 
- [x] https://github.com/sealerio/sealer/issues/1986 @kakaZhou719
