### ISSUE TITLE
[Task List] 0.10.0 Release - 20230430

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#2126]
### New Features 
- [x] support run sealer app image independently. https://github.com/sealerio/sealer/issues/2208
- [x] support render app image file using env（https://github.com/sealerio/sealer/issues/2017 ）@kakaZhou719 
- [ ] OCI registry support （https://github.com/sealerio/sealer/pull/2071 ）@jsparter
~~4. sealer config file support（https://github.com/sealerio/sealer/issues/2123 )~~ @kakaZhou719 
- [x] sealer rollback feature support （https://github.com/sealerio/sealer/pull/2115 ）@wizardlyk
- [x] sealer support `ENV` and `APPENV`  at kubefile @kakaZhou719 https://github.com/sealerio/sealer/pull/2179
- [x] sealer  support pack different arch image @kakaZhou719 https://github.com/sealerio/sealer/issues/2176
### Stability

- [ ] ~~stability for sealer official image: cluster installation , app launch, and  sealer official website related document : `quickstart`, `concept/clusterfile`.@Stevent-fei~~
- [ ] sealer cmd code optimization, especially for cluster types cmd.（https://github.com/sealerio/sealer/issues/2124 ）@Starnop

### Ease to use

- [ ] add several best practices to plugin repo.(https://github.com/sealerio/plugins )@Stevent-fei @Starnop 

### Performance
- [x] sealer image distribution efficiency, support image cache mode.(https://github.com/sealerio/sealer/issues/2010 )@kakaZhou719
- [x] disk space usage when sealer image load. （https://github.com/sealerio/sealer/issues/2109 ）@kakaZhou719

### Bugfix
not list here.

### Long-term task
- [ ] support k3s and k0s :https://github.com/sealerio/sealer/issues/1770 @starComingup 
- [ ] the integration of kyverno https://github.com/sealerio/sealer/issues/1899  @YTGhost
- [ ] P0 https://github.com/sealerio/sealer/issues/2100 @kakaZhou719 

### Others

more details to see: https://github.com/sealerio/sealer/milestone/11

Type: *feature request*
