### ISSUE TITLE
[Task List] 0.11.0 Release

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#2228]
### New Features 
- [ ] support run sealer app image independently. https://github.com/sealerio/sealer/issues/2208
- [ ] OCI registry support （https://github.com/sealerio/sealer/pull/2071 ）@jsparter
- [ ] customize sealer root directory(/var/lib/sealer) @kakaZhou719 
- [ ] Support abbreviated image name (https://github.com/sealerio/sealer/issues/2152) @jsparter
- [ ] support run sealer image locally (https://github.com/sealerio/sealer/issues/2087) @Daz-3ux
- [ ]  Support to merge sealer images @kakaZhou719 

### Stability

- [ ] stability for sealer official image: cluster installation , app launch, and  sealer official website related document : `quickstart`, `concept/clusterfile`.@kakaZhou719
- [ ] sealer cmd code optimization, especially for cluster types cmd.（https://github.com/sealerio/sealer/issues/2124 ）@kakaZhou719

### Ease to use

- [ ] add several best practices to plugin repo.(https://github.com/sealerio/plugins )@kakaZhou719

### Bugfix
- [ ] lost image name after sealer load @kakaZhou719 
- [ ] https://github.com/sealerio/sealer/issues/2022 @kakaZhou719 
- [ ] https://github.com/sealerio/sealer/issues/2210 @kakaZhou719 
- [ ] no need to merge kubeadm.yaml(from sealer image) with built-in kubeadm(from sealer code) https://github.com/sealerio/sealer/issues/2226 @kakaZhou719 
- [ ] https://github.com/sealerio/sealer/issues/2195 @kakaZhou719 

### Long-term task
- [ ] support k3s and k0s :https://github.com/sealerio/sealer/issues/1770 @starComingup 
- [ ] the integration of kyverno https://github.com/sealerio/sealer/issues/1899  @YTGhost
- [ ] P0 https://github.com/sealerio/sealer/issues/2100 @kakaZhou719 

### Others

more details to see: https://github.com/sealerio/sealer/milestone/14

Type: *feature request*
